  version: '2'
  services:
   web:
     image: node:6.0
     volumes:
       - ./:/usr/src/app
     working_dir: /usr/src/app
     command: sh -c 'npm start'
     ports:
      - "3000:3000"
     volumes:
      - .:/usr/src/app

